version: '3.9'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
